### ISSUE TITLE
Reproduce lbryum#155 on regtest and document it (and maybe save wallet that is not being restored correctly)

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/grooming#10]
lbryio/lbryum#155

After repro, update issue with next steps

**Comment by shyba** [comment]
@lyoshenka 
Since it can lead to loss of funds, instead of saving a lost wallet I created regression tests for it: https://github.com/shyba/lbrytest/tree/tests_for_backups

I hope they turn to be valuable in solving the issue, but I don't know if it's worth merging into lbrytest.

**Comment by shyba** [comment]
Pushed regression tests into a branch: https://github.com/lbryio/lbrytest/tree/tests_for_backups
Comment added, which closes this issue on being able to reproduce it.
