### ISSUE TITLE
Get docs working with Travis

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/grooming#22]

**Comment by hackrush01** [comment]
**From slack DM**

ok here's how i think it should work
we need to require mkdocs as a dev requirement
then we should run the gen_api_docs script and have it generate the markdown files into a temp directory
then run `mkdocs build` to build the html and put it into /docs
this should all happen by running a single script
so maybe that can be the last step of gen_api_docs
so /docs gets checked into git, but the intermediate dir with the markdown files does not
then, as part of travis's tests, travis should call the gen_api_docs script and check if the /docs dir has any  changes in it
if it does, travis should fail the build and print a message like "run gen_api_docs and commit the changes"
this way, docs changes always go in the same PR as code changes
they get merged together
nothing is out of sync
and we can server https://lbryio.github.io/lbry/ out of the docs dir
as soon as the code is pushed, the online docs will update
now IDEALLY, the docs should be versioned just like the daemon is versioned, so they match our releases. but that's for another time

**Comment by alyssaoc** [comment]
closed in favor of https://github.com/lbryio/lbry/pull/1132
