### ISSUE TITLE
Register different API functions at different stages of startup.

### ISSUE THREAD

**Issue by hackrush01** [lbryio/grooming#27]
For lbryio/lbry#1121
This would allow the API calls to be made before the completion of startup. And the functions requiring specific component will be registered when the component has been loaded. This will be probably be realized using decorators.

## this iteration

- [x] research what things need to be moved and such (3 pts)
- [x] dht (5 pts)
- [x] file manager (5 pts)

## next iteration

- [x] rationalize component stuff
- [x] peer protocol factory (3)
- [x] reflector protocol factory (3)
- [x] update tests (5)
- [x] actually do what the title says (7)

## next-er iteration
- [x] write tests(I HATE THEM SO FAR!!! but I've been told it gets better) (5+5)
- [x] knock out the last thing with component (1)

**Comment by hackrush01** [comment]
- [x] write the decorator function (7)
- [x] list the components (3)
- [x] figure out which calls require which components (3)
- [x] update component logic to register API functions using decorators one at a time (5)

**Comment by hackrush01** [comment]
Method | Components Required
------------ | -------------
blob_announce            |
blob_availability        |
blob_delete              |
blob_get                 |
blob_list                |
blob_reflect             |
blob_reflect_all         |
block_show               |
channel_export           |
channel_import           |
channel_list             |
channel_new              |
claim_abandon            |
claim_list               |
claim_list_by_channel    |
claim_list_mine          |
claim_new_support        |
claim_renew              |
claim_send_to_address    |
claim_show               |
commands                 |
daemon_stop              |
file_delete              |
file_list                |
file_reflect             |
file_set_status          |
get                      |
help                     |
peer_list                |
publish                  |
resolve                  |
resolve_name             |
routing_table_get        |
settings_get             |
settings_set             |
status                   |
stream_availability      |
stream_cost_estimate     |
transaction_list         |
transaction_show         |
utxo_list                |
version                  |
wallet_balance           |
wallet_decrypt           |
wallet_encrypt           |
wallet_is_address_mine   |
wallet_list              |
wallet_new_address       |
wallet_prefill_addresses |
wallet_public_key        |
wallet_send              |
wallet_unlock            |
wallet_unused_address    |

**Comment by hackrush01** [comment]
Method | Components Required
------------ | -------------
blob_announce            | session
blob_availability        | session
blob_delete              | session
blob_get                 | session 
blob_list                | session
blob_reflect             | session
blob_reflect_all         | session
block_show               | session
channel_export           | session
channel_import           | session
channel_list             | session
channel_new              | session
claim_abandon            | session
claim_list               | session
claim_list_by_channel    | session
claim_list_mine          | session
claim_new_support        | session
claim_renew              | session
claim_send_to_address    | session
claim_show               | session
commands                 | allowed_during_startup
daemon_stop              | end
file_delete              | file_manager
file_list                | file_manager
file_reflect             | file_manager
file_set_status          | file_manager
get                      | file_manager
help                     | allowed_during_startup
peer_list                | session
publish                  | file_manager
resolve                  | session
resolve_name             | session
routing_table_get        | session
settings_get             | allowed_during_startup
settings_set             | allowed_during_startup
status                   | allowed_during_startup
stream_availability      | session
stream_cost_estimate     | session
transaction_list         | session
transaction_show         | session
utxo_list                | session
version                  | allowed_during_startup
wallet_balance           | session
wallet_decrypt           | session
wallet_encrypt           | session
wallet_is_address_mine   | session
wallet_list              | session
wallet_new_address       | session
wallet_prefill_addresses | session
wallet_public_key        | session
wallet_send              | session
wallet_unlock            | session
wallet_unused_address    | session

**Comment by jackrobison** [comment]
I think `session` should be split into `wallet` and `dht` components. Additionally, it should be possible to depend on multiple components - like `publish` should depend on `wallet` and `file_manager`

**Comment by kauffj** [comment]
@hackrush01 @jackrobison can I cause weird bugs by changing settings in the middle of function execution? Are we writing our code in such a way that setting values are stored and the same value is used for any given command/function execution?

**Comment by jackrobison** [comment]
@kauffj the settings are a global variable, so all classes/functions use the same settings. That said, changing them mid-setup could cause weird bugs, yes (such as changing the wallet directory after it started up)

**Comment by kauffj** [comment]
@jackrobison consider two function designs:

```
func dangerFunc()
{
  yield func1(SETTINGS.FOO);
  yield func2();
  yield func3(SETTINGS.FOO); //this function is related to func1
}
```

```
func safeFunc()
{
  foo = SETTINGS.FOO;
  yield func1(foo);
  yield func2();
  yield func3(foo);
}
```
