### ISSUE TITLE
provide chainquery feedback

### ISSUE THREAD

**Issue by bones7242** [lbryio/grooming#54]

**Comment by bones7242** [comment]
note to self: essentially imagine doing the queries I am currently doing with spee.ch via chainquery

**Comment by kauffj** [comment]
@lyoshenka @tiger5226: @billbitt is considering this blocked until latest round of feedback/changes to chainquery is adopted. Please update once done or if that is incorrect advice.

**Comment by kauffj** [comment]
@lyoshenka can you please clarify what (if any) pending changes exist beyond those discussed [here]( https://github.com/lbryio/chainquery/issues/35#issuecomment-396635692)?

Nothing in there seems like it ought to block this, but I thought there were desired changes related to the claim parts of it.

**Comment by tiger5226** [comment]
I do think [this](https://github.com/lbryio/chainquery/issues/32) is also important for @billbitt . It is related to the bid state of a claim being correct.

**Comment by lyoshenka** [comment]
main changes are getting the schema right and ensuring that we're dealing with reorgs correctly. id like to see tests for reorg scenarios - that should help us make sure we got it right
