### ISSUE TITLE
app thumbnail uploads (from mac?) result in broken links on spee.ch

### ISSUE THREAD

**Issue by bones7242** [lbryio/grooming#67]
for certain publishes made via the app (from macs?), the thumbnail appears or is broken on spee.ch
- example: https://spee.ch/4b1567a9015c5d97739970213346bb516a2219a6/rBtfkpiLmVMrUqxTNYcHOe4z.png
- the images do seem to unfurl in slack
- the image is not served properly to the app (although some might be served ok, e.g. cryptocandor)
- the File record created in MySQL shows 'blob' for the file name but shows a hash in the file path:

```
name: rBtfkpiLmVMrUqxTNYcHOe4z	
claimId: 4b1567a9015c5d97739970213346bb516a2219a6	
...	
fileName: blob	
filePath: /home/lbry/Uploads/Y8gLfOte2zq1_9ISePg-ytWY	
fileType: image/png	
...
```

**Comment by bones7242** [comment]
@tzarebczan @seanyesmunt fyi

**Comment by bones7242** [comment]
I'm thinking this has to do with the publish route's middleware parsing the formdata from the publish request.  Perhaps starting the publish before it has all of the file, or something like that.

**Comment by bones7242** [comment]
@tzarebczan do you have an example uri for a video that was published from the app and _did_ work correctly? I'd like to compare.  Otherwise, I'll do a test upload from my app.

**Comment by tzarebczan** [comment]
Here's a JPG that worked: https://spee.ch/37cd0ab1b52b55b4eb04849fb9f6769c51180184/kCutEbo5xJeeOZLJOPHBVmQT.jpg

**Comment by bones7242** [comment]
ugh, I meant to make this issue on `lbryio/spee.ch` not `lbryi/grooming`

**Comment by bones7242** [comment]
Issue moved to [lbryio/spee.ch #507](https://github.com/lbryio/spee.ch/issues/507) via [**ZenHub**](https://www.zenhub.com/)
